__BASE__: "{fileDirname}/base.yaml"

ENVIRONMENT:
  MAX_EPISODE_STEPS: 200

DATASET:
  DATA_PATH: "data/datasets/rearrange/v3/set_table_220417_{split}.json.gz"

TASK:
  TYPE: RearrangeOpenFridgeTask-v0
  USE_MARKER_T: False
  SPAWN_REGION: [[0.933, -0.6], [1.833, 0.6]]
  BASE_NOISE: 0.1
  BASE_ANGLE_NOISE: 0.25

  POSSIBLE_ACTIONS:
    - BaseArmGripperAction
    - BaseArmGripperAction2

  SENSORS:
    - ArmJointPositionSensor
    - GripperPositionSensor
    - IsGraspedSensor
    - PickGoalSensor
    - PickGoalSensor2

  MEASUREMENTS:
    - GripperToMarkerDistance
    - GripperToRestingDistance
    - MarkerToGoalDistance
    - SetMarkerSuccess
    - RearrangeSetSuccess
    - GripperStatus
    - InvalidGraspPenalty
    - InRegion
    - OutOfRegionPenalty
    - CollisionPenalty
    - RearrangeSetMarkerReward
  GripperToMarkerDistance:
    TYPE: GripperToMarkerDistance
  GripperToRestingDistance:
    TYPE: GripperToRestingDistance
  MarkerToGoalDistance:
    TYPE: MarkerToGoalDistance
    USE_ABS: False
  SetMarkerSuccess:
    TYPE: SetMarkerSuccess
    THRESHOLD: 0.15
  RearrangeSetSuccess:
    TYPE: RearrangeSetSuccess
    THRESHOLD: 0.15
  GripperStatus:
    TYPE: GripperStatusV1
  InvalidGraspPenalty:
    TYPE: InvalidGraspPenalty
    THRESHOLD: 0.2
    PENALTY: 1.0
    END_EPISODE: True
  InRegion:
    TYPE: InRegion
    ALLOWED_REGION: [[0.333, -1.6], [2.333, 1.6]]
    REF_ART_OBJ: "fridge_:0000"
  OutOfRegionPenalty:
    TYPE: OutOfRegionPenalty
    PENALTY: 1.0
    END_EPISODE: True
  # Avoid undesired behaviors (like penetration)
  CollisionPenalty:
    TYPE: CollisionPenalty
    PENALTY: 1.0
    MAX_FORCE: 5000
  RearrangeSetMarkerReward:
    TYPE: RearrangeSetMarkerReward
    DIST_REWARD: 2.0
    SUCC_REWARD: 0.0
    PICK_REWARD: 1.0
    PICK_PENALTY: 1.0
    END_PICK_WRONG: True
    DROP_REWARD: 1.0
    DROP_PENALTY: 0.0
    END_DROP: True
